[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
for = "/.well-known/assetlinks.json"
[headers.values]
Cache-Control = '''
    public,
    max-age=0'''
Content-Type = "application/json"
X-Content-Type-Options = "nosniff"

[[redirects]]
from = "/.well-known/*"
to = "/well-known/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false