[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
from = "/.well-known/*"
to = "/well-known/index.html"
status = 200

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
    enable = false